name: "01_S3Bucket"
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/FeatureBranch1'
    uses: marufaus/ReusableWorkflow123/.github/workflows/aws_tf_plan.yml@FeatureBranch1
    with:
      path: S3Bucket
      tf_vars_file: dev.tfvars
      gh_environment: dev

  Deploy_Dev:
    needs: Plan_Dev
    uses: marufaus/ReusableWorkflow123/.github/workflows/aws_tf_apply.yml@FeatureBranch1
    with:
      path: S3Bucket
      tf_vars_file: dev.tfvars
      gh_environment: dev

    steps:
      - name: Configure AWS credentials (OIDC) - Dev Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.DEV_ACCOUNT_ID }}:role/OrganizationAccountAccessRole
          role-session-name: GitHub-OIDC-TERRAFORM
          aws-region: ${{ secrets.AWS_REGION }}

  Plan_Uat:
    if: github.ref == 'refs/heads/main'
    uses: marufaus/ReusableWorkflow123/.github/workflows/aws_tf_plan.yml@main
    with:
      path: S3Bucket
      tf_vars_file: prod.tfvars
      gh_environment: prod

  Deploy_Uat:
    needs: Plan_Uat
    uses: marufaus/ReusableWorkflow123/.github/workflows/aws_tf_apply.yml@main
    with:
      path: S3Bucket
      tf_vars_file: prod.tfvars
      gh_environment: prod

    steps:
      - name: Configure AWS credentials (OIDC) - UAT Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.UAT_ACCOUNT_ID }}:role/OrganizationAccountAccessRole
          role-session-name: GitHub-OIDC-TERRAFORM
          aws-region: ${{ secrets.AWS_REGION }}
